// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgehuxmzjndgqgostyxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZWh1eG16am5kZ3Fnb3N0eXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDE5MDIsImV4cCI6MjA3MDQ3NzkwMn0.hLUWM7obo3SMnsg0RJj0U_VcpaUr3L-2xXKrCebumBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});